version: '3'

services:
  localstack:
    container_name: ${LOCALSTACK_DOCKER_NAME-localstack_main}
    image: localstack/localstack
    network_mode: bridge
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - SERVICES=${SERVICES-s3,sqs}
      - DEBUG=${DEBUG-1}
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock